;;; init-elfeed.el --- elfeed config -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:




(use-package elfeed
  :custom
  (elfeed-search-filter "@8days +unread")
  (elfeed-confirm-browse-url nil)
  (elfeed-search-separator-date-format "%Y-%m-%d")
  (elfeed-curl-timeout 60)
  (elfeed-search-title-max-width 100)
  (elfeed-curl-max-connections 32)
  (elfeed-db-directory "~/.elfeed/")
  :bind ((:map elfeed-search-mode-map
               ("f" . elfeed-update-feed)
               ("t" . spike-leung/elfeed-toggle-unread)
               ("T" . elfeed-tree)
               ("Z" . spike-leung/elfeed-reading-list)))
  :config
  (setq elfeed-feeds
        '(("https://taxodium.ink/rss.xml" :title "Taxodium")
          ("https://protesilaos.com/master.xml" :title "Protesilaos" emacs)
          ("https://hollie.eilloh.net/rss.xml" :title "Small Good Things")
          ("https://leehenry.top/rss.xml" :title "伏枥之间" blaugust2026)
          ("https://chlo.is/feed.atom" :title "园子里的日光")
          ("https://www.geedea.pro/index.xml" :title "极客死亡计划")
          ("https://blog.southfox.me/feed.xml" :title "狐狸反走矣")
          ("https://blog.cytrogen.icu/atom.xml" :title "Cytrogen")
          ("https://www.stefanjudis.com/rss.xml" :title "Stefan Judis" weekly frontend)
          ("https://www.sanityinc.com/feed.xml" :title "Steve Purcell" emacs)
          ("https://blog.prayhand13013.top/rss.xml" :title "Tomoe Mami" emacs)
          ("https://tracydurnell.com/feed/atom/" :title "Tracy Durnell's Mind Garden")
          ("https://yangbear.bearblog.dev/feed/" :title "YangBear" 台湾)
          ("https://wangyurui.com/feed.xml" :title "太隐" :fetch-link t)
          ("https://www.laomuzhu.cn/feed/" :title "木竹")
          ("https://trashposts.com/rss.xml" :title "廢文小天地" 台湾)
          ("https://blog.verdant.ee/atom.xml" :title "映屿" weekly)
          ("https://www.linggandianbo.com/rss/" :title "灵感电波" weekly)
          ("https://z.arlmy.me/atom.xml" :title "素生" blaugust2026)
          ("https://blog.giveanornot.com/index.xml" :title "資工小廢物 - JN")
          ("https://ro3or.com/index.xml" :title "鹅玉") ;; new domain: https://eyu.at/
          ("https://anniemueller.com/posts_feed" :title "annie")
          ("https://polebug.github.io/atom.xml" :title "Polebug")
          ("https://www.pseudoyu.com/feed.xml" :title "Pseudoyu")
          ("https://blog.pursuitus.com/feed" :title "Ouroboros")
          ("https://clandestini.org/feed/" :title "clandestini.org" 葡萄牙语)
          ;; Email: 3hl5jx56nh55vdvwhoh1@kill-the-newsletter.com
          ("https://kill-the-newsletter.com/feeds/3hl5jx56nh55vdvwhoh1.xml" :title "kill-the-newsletter@taxodium" weekly)
          ("https://takeonrules.com/index.xml" :title "Jeremy Friesen" emacs writing)
          ("https://blog.cosine.ren/rss.xml" :title "FE Bits 前端周周谈" weekly frontend)
          ("https://blog.ursb.me/feed.xml" :title "Airing 的博客")
          ("https://axxuy.xyz/blog/feed.xml" :title "Axxuy.xyz")
          ("https://www.yozblog.com/index.xml" :title "DrummerYoZ 鼓手柚子" 台湾)
          ("https://i.hsfzxjy.site/rss.xml" :title "#hsfzxjy#")
          ("https://1sle29.github.io/index.xml" :title "1sle")
          ("https://pathos.page/feed.xml" :title "2750 words")
          ("https://61.life/feed.xml" :title "61's life")
          ("http://antirez.com/rss" :title "<antirez>" tech)
          ("https://1900.live/rss/" :title "@1900")
          ("https://anerdyfujocries.wordpress.com/feed/" :title "A Nerdy Fujo Cries")
          ("https://scripter.co/index.xml" :title "A Scripter's Notes" tech emacs)
          ("https://gkeenan.co/avgb/feed.xml" :title "A Very Good Blog by Keenan")
          ("https://www.achilletoupin.com/feed.xml" :title "Achille Toupin" 法语 裁缝)
          ("https://alexwlchan.net/atom.xml" :title "Alex Chan" tech)
          ("https://alex.party/rss.xml" :title "Alex.Party" frontend)
          ("https://anarchaeopteryx.bearblog.dev/feed/" :title "An Archaeopteryx" blaugust2026)
          ("https://andrewkelley.me/rss.xml" :title "Andrew Kelley" code zig)
          ("https://manateelazycat.github.io/feed.xml" :title "Andy Stewart" emacs)
          ("https://www.galactanet.com/feed.xml" :title "Andy Weir's Writing" writing)
          ("https://anotherdayu.com/feed/" :title "Another Dayu")
          ("https://antfu.me/feed.xml" :title "Anthony Fu" frontend)
          ("https://aresluna.org/main.rss" :title "Aresluna")
          ("https://arialdomartini.github.io/feed.xml" :title "Arialdo on Code" emacs tech)
          ("https://lucumr.pocoo.org/feed.atom" :title "Armin Ronacher's Thoughts and Writings")
          ("https://expensive.toys/rss.xml" :title "Artur Bień" emacs frontend css)
          ("https://atpx.com/feed.xml" :title "atpX")
          ("https://jeddacp.me/feed/" :title "august morning" photo blaugust2026)
          ("https://blog.august.hk/rss.xml" :title "August's Blog")
          ("https://baxy.typlog.io/feed.xml" :title "BAXY")
          ("https://whimsies.bearblog.dev/feed/" :title "Before 30")
          ("https://bens.love/feed" :title "Ben's Love")
          ("https://bitfieldconsulting.com/posts?format=rss" :title "Bitfield Consulting" tech go)
          ("https://blakewatson.com/feed.xml" :title "Blake Watson")
          ("https://blogblog.club/blog/rss.xml" :title "BlogBlog 同樂會")
          ("https://bluepika.life/rss.xml" :title "Bluepikachu")
          ("https://garden.bradwoods.io/rss.xml" :title "Brad Woods Digital Garden")
          ("http://ozark.hendrix.edu/~yorgey/forest/005U/atom.xml" :title "Brent A. Yorgey's Weeknotes" weekly)
          ("https://bryn.codes/feed.xml" :title "Bryn Newell")
          ("https://cbvivi.today/feed.xml" :title "cbvivi")
          ("https://openpath.quest/feed.xml" :title "Chad Whitacre")
          ("https://yuanchaofa.com/" :title "Chaofa Yuan")
          ("https://chise.hachiroku.com/zh/feed/atom" :title "Chise Hachiroku")
          ("https://conge.livingwithfcs.org/feed.xml" :title "Conge" running)
          ("https://css-irl.info/rss.xml" :title "CSS In Real Life"  frontend css web)
          ("https://feedpress.me/cssweekly" :title "CSS Weekly" weekly frontend)
          ("https://dbushell.com/rss.xml" :title "dbushell.com" frontend)
          ("https://www.densediscovery.com/feed/" :title "Dense Discovery" weekly)
          ("https://sive.rs/en.atom" :title "Derek Sivers")
          ("https://soatok.blog/feed/" :title "Dhole Moments" tech security cryptography)
          ("https://divergentrays.com/blog/blogfeed.xml" :title "Divergent Rays" weekly 宝石)
          ("https://diygod.cc/feed" :title "DIYgod")
          ("https://notes.druchan.com/feed.xml" :title "druchan")
          ("https://dylanbeattie.net/rss" :title "dylanbeattie.net")
          ("https://ege.celikci.me/feed.atom" :title "ege.celikci.me")
          ("https://elizen.me/index.xml" :title "Elizen")
          ("https://emacsformacosx.com/atom/release" :title "Emacs For Mac OS X: Releases RSS Feed")
          ("https://emacsredux.com/atom.xml" :title "Emacs Redux" emacs)
          ("https://emilygorcenski.com/index.xml" :title "Emily Gorcenski")
          ("https://entropicthoughts.com/feed" :title "Entropic Thoughts" tech)
          ("https://boehs.org/in/blog.xml" :title "Evan Boehs in the blog" emacs tech)
          ("https://falseknees.com/rss.xml" :title "false knees" anime manga)
          ("https://ferd.ca/feed.rss" :title "Ferd.ca" tech)
          ("https://borretti.me/feed.xml" :title "Fernando Borretti")
          ("https://fhur.me/feed.xml" :title "fhur's blog" tech)
          ("https://filiph.net/text/atom.xml" :title "filiph.net/text" tech)
          ("https://forkingmad.blog/feed/" :title "Forking Mad")
          ("https://yovey.me/feed/" :title "Fragments")
          ("https://rscottjones.com/feed/" :title "from rscottjones")
          ("https://cprss.s3.amazonaws.com/frontendfoc.us.xml" :title "Frontend Focus" weekly)
          ("https://blog.gentlelucky.com/zh/index.xml" :title "GentleLucky" weekly)
          ("https://ginoz.bearblog.dev/feed/" :title "GINOZ's Blog")
          ("https://gobino.be/feed/" :title "gobino's bites" weekly)
          ("https://grantslatton.com/rss.xml" :title "Grant Slatton's Blog" writing tech)
          ("https://herman.bearblog.dev/feed/" :title "Herman's blog" blog)
          ("https://heydingus.net/feed.rss" :title "HeyDingus" weekly)
          ("https://www.hillelwayne.com/" :title "Hillel Wayne" tech)
          ("http://html5doctor.com/feed/" :title "HTML5 doctor" weekly frontend)
          ("https://www.icebeer.top/feed/" :title "IceBeer")
          ("https://egh0bww1.com/rss.xml" :title "include-yy's blog" emacs)
          ("https://blog.gzj.life/zh-cn/index.xml" :title "ISouthRain Blog" emacs)
          ("https://j3s.sh/feed.atom" :title "j3s.sh")
          ("https://veryjack.com/feed/" :title "Jack's Space")
          ("https://talk.jackalope.city/feed/" :title "jackalope.city")
          ("https://jakearchibald.com/posts.rss" :title "Jake Archibald's blog" frontend)
          ("https://jakelazaroff.com/rss.xml" :title "jakelazaroff.com" frontend css web)
          ("https://jason-memo.dev/feed/feed.xml" :title "Jason Chen" tech)
          ("https://jasonfantl.com/feed.xml" :title "Jason Fantl" science)
          ("https://cprss.s3.amazonaws.com/javascriptweekly.com.xml" :title "JavaScript Weekly" weekly frontend)
          ("https://www.jayeless.net/index.xml" :title "Jayeless.net" 数字花园)
          ("https://jeffbradberry.com/feeds/all.atom.xml" :title "Jeff Bradberry" emacs)
          ("https://jetgirl.art/rss/" :title "JetGirlArt")
          ("https://blog.jim-nielsen.com/feed.xml" :title "Jim Nielsen" tech)
          ("https://www.joshwcomeau.com/rss.xml" :title "Josh Comeau" frontend css web)
          ("https://hamatti.org/feed/feed.xml" :title "Juhis" blaugust2026)
          ("https://jvns.ca/atom.xml" :title "Julia Evans" tech)
          ("https://karthinks.com/index.xml" :title "Karthinks" emacs)
          ("https://kayleerowena.com/rss.xml" :title "Kaylee Rowena" weekly)
          ("https://kedara.eu/blog/index.xml" :title "Kedara.eu" blaugust2026)
          ("https://marisabel.nl/feeds/blog.php" :title "Konfetti Explorations (Blog only)")
          ("https://kristofferbalintona.me/articles/feed.xml" :title "Kristoffer Balintona" emacs tech)
          ("https://l1uyun.one/atom.xml" :title "l1uyun's Blog")
          ("https://laike9m.com/blog/rss/" :title "laike9m's blog")
          ("https://lars-christian.com/feed.xml" :title "Lars-Christian's website")
          ("https://www.teamten.com/lawrence/writings/rss.xml" :title "Lawrence Kesteloot's writings")
          ("https://ldbeth.sdf.org/rss.xml" :title "LdBeth" emacs)
          ("https://lea.verou.me/feed.xml" :title "Lea Verou"  frontend web)
          ("https://www.less-bug.com//index.xml" :title "Less Bug" tech)
          ("https://www.lukew.com/ff/rss" :title "LukeW" design)
          ("https://lynn.sh/rss.xml" :title "Lynn" emacs)
          ("https://markentier.tech/feed.rss.xml" :title "markentier.tech" tech rust)
          ("https://matklad.github.io/feed.xml" :title "matklad" tech)
          ("https://mtwb.blog/index.xml" :title "Matt's Blog" blaugust2026)
          ("https://endler.dev/rss.xml" :title "Matthias Endler" tech)
          ("https://matthiasott.com/rss" :title "Matthias Ott" weekly)
          ("https://michal.sapka.pl/rss.xml" :title "Michał M. Sapka")
          ("https://renkotsuban.com/rss.xml" :title "Midnight Dreaming")
          ("https://renkotsuban.com/rss.xml" :title "Midnight Reading" weekly)
          ("https://bilibi.li/feed.rss" :title "midnight serial experiments")
          ("https://monocyte.bearblog.dev/feed/" :title "monocyte's blog")
          ("https://www.murilopereira.com/feed.atom" :title "Murilo Pereira" emacs)
          ("https://musicforprogramming.net/rss.xml" :title "Music For Programming")
          ("https://neurofrontiers.blog/feed/" :title "Neurofrontiers" weekly)
          ("https://nik.digital/rss.xml" :title "Niklas Gadermann" frontend)
          ("https://cprss.s3.amazonaws.com/nodeweekly.com.xml" :title "Node Weekly"  weekly frontend)
          ("https://notes.jeddacp.com/feed/" :title "Notes by JCProbably")
          ("https://nothingissimple.ablatedsprocket.com/rss.xml" :title "Nothing Is Simple" emacs tech)
          ("https://onevcat.com/feed.xml" :title "OneV's Den")
          ("https://overreacted.io/rss.xml" :title "overreacted" frontend react)
          ("https://www.owenyoung.com/atom.xml" :title "owenyoung")
          ("https://enocc.com/feed.xml" :title "Pablo Enoc")
          ("https://www.parkerchang.life/feed.xml" :title "Parker Chang's Web" 台湾)
          ("http://www.aaronsw.com/2002/feeds/pgessays.rss" :title "Paul Graham" tech)
          ("https://manuelmoreale.com/feed/peopleandblogs" :title "Piri")
          ("https://plainvanillaweb.com/blog/feed.xml" :title "Plain Vanilla Blog" tech)
          ("https://www.yuqiqin.me/feed.xml" :title "Psychic Paper" english)
          ("https://randomascii.wordpress.com/feed/" :title "Random ASCII – tech blog of Bruce Dawson" tech)
          ("https://lutaonan.com/rss.xml" :title "Randy's Blog")
          ("https://www.raptitude.com/feed/" :title "Raptitude")
          ("https://rknight.me/subscribe/posts/atom.xml" :title "Robb Knight")
          ("https://robbowen.digital/feed.xml" :title "Robb Owen Digital" tech)
          ("https://rseeber.github.io/blog/feed.xml" :title "Rseeber" tech)
          ("https://ryanmulligan.dev/feed.xml" :title "Ryan Mulligan" frontend)
          ("https://sachachua.com/blog/feed/index.xml" :title "Sacha Chua" emacs)
          ("https://samsharp.bearblog.dev/feed/" :title "sam's internet house")
          ("https://www.sarasoueidan.com/blog/index.xml" :title "Sara Soueidan" frontend ui)
          ("https://scyy.fi/index.xml" :title "Sarabet Chang Yuye")
          ("https://sebastiano.tronto.net/blog/feed.xml" :title "Sebastiano Tronto's blog" tech)
          ("https://shuojen.com/blog/rss.xml" :title "Shuo-jen Huang" 台湾)
          ("https://shuyulin1127.comb/feed/" :title "Shuyu Pixelart" 台湾)
          ("https://sightlessscribbles.com/feed.xml" :title "Sightless Scribbles")
          ("https://song.al/feed.xml" :title "Simon" 日本)
          ("https://hojberg.xyz/rss.xml" :title "Simon Højberg" frontend)
          ("https://simonwillison.net/atom/everything/" :title "Simon Willison")
          ("https://sindresorhus.com/rss.xml" :title "Sindre Sorhus" frontend)
          ("https://smallcypress.bearblog.dev/feed" :title "Small Cypress")
          ("https://susam.net/feed.xml" :title "Susam Pal")
          ("https://ayu.land/atom.zh.xml" :title "Sweetfish Ayu")
          ("https://syls.blog/feed/" :title "Syl's Blog")
          ("https://tao.zz.ac/feed.xml" :title "Tao")
          ("https://www.technbuzz.com/feed/" :title "Technbuzz" frontend)
          ("https://technicalwriting.dev/rss.xml" :title "technicalwriting.dev" tech)
          ("https://taonaw.com/feed.xml" :title "The Art Of Not Asking Why" emacs)
          ("https://www.autodidacts.io/rss/" :title "The Autodidacts" weekly)
          ("https://chrismaiorana.com/feed/" :title "The Daily Macro" emacs)
          ("https://listeningroomsmusic.com/feed/?type=rss" :title "The Listening Rooms")
          ("https://feedpress.me/thetechnium" :title "The Technium")
          ("https://thewanderingallison.vercel.app/rss.xml/" :title "The Wandering Allison")
          ("https://theworksofegan.net/feed.xml" :title "The Works of Egan")
          ("https://themkat.net/feed.xml" :title "TheMKat’s blog" emacs)
          ("https://thetangent.space/feed.xml" :title "theTangentSpace" weekly blaugust2026)
          ("https://johnrakestraw.com/index.xml" :title "thinking out loud" writing emacs)
          ("https://feeds.feedburner.com/thoughtsfromtheredplanet?format=xml" :title "thoughts from the red planet" tech)
          ("https://tianheg.co/index.xml" :title "Tianhe Gao")
          ("https://mazzzystar.github.io/atom.xml" :title "TL;DR")
          ("https://owlswims.com/feed/" :title "To the Lighthouse")
          ("https://tusharhero.codeberg.page/rss.xml" :title "tusharhero" emacs)
          ("https://www.paddysun.top/feed" :title "Under the Sun with Paddy")
          ("https://emacsninja.com/emacs.atom" :title "Vasilij Schneidermann" emacs)
          ("https://blog.videah.net/atom.xml" :title "videah's blog")
          ("https://waitbutwhy.com/feed" :title "Wait But Why")
          ("https://www.marginalia.nu/log/index.xml" :title "Weblog on marginalia.nu")
          ("https://webmention.io/api/mentions.atom?token=qcwPCX61g9khbvZWp3U0qg" :title "webmention.io" webmention)
          ("https://labnotes.org/rss/" :title "Weekend Reading" weekly)
          ("https://weiwei.place/feed" :title "Weiwei Xu")
          ("https://what-if.xkcd.com/feed.atom" :title "what if?.xkcd" weekly)
          ("https://blog.itswincer.com/atom.xml" :title "Wincer's Blog")
          ("https://next.xeonzilla.top/atom.xml" :title "x7aNote")
          ("https://xenodium.com/rss.xml" :title "xenodium" emacs)
          ("https://xuanwo.io/index.xml" :title "Xuanwo's Blog" tech)
          ("https://your-local-grubdog.neocities.org/feed.xml" :title "Your Local Grubdog")
          ("https://zine.milliesquilly.com/rss.xml" :title "zine of millie" weekly cool)
          ("https://keelii.com/atom.xml" :title "临池不辍")
          ("https://www.yunyoujun.cn/atom.xml" :title "云游君" frontend)
          ("https://jt26wzz.com/rss.xml" :title "从不说安全词" tech)
          ("https://www.ftium4.com/rss.xml" :title "体验碎周报 - 龙爪槐守望者"  weekly design ux)
          ("https://archive.casouri.cc/rock/day/atom.xml" :title "余日摇滚" music)
          ("https://joeytoday.com/rss.xml" :title "偶然时刻" weekly)
          ("https://echosoar.github.io/weekly/atom.xml" :title "偷懒爱好者周刊" weekly)
          ("https://luszy.com/home/feed/" :title "冬天里的向日葵")
          ("https://www.kawabangga.com/feed" :title "卡瓦邦噶！" tech)
          ("https://yinji.org/feed" :title "印记")
          ("http://www.ruanyifeng.com/blog/atom.xml" :title "阮一峰的网络日志" weekly)
          ("https://jesor.me/feed.xml" :title "大破进击")
          ("https://spacexcode.com/blog/rss.xml" :title "太空编程 Blog" frontend)
          ("https://wenshan.home.blog/feed/" :title "文山随笔")
          ("https://blog.mfwt.top/index.php/feed/" :title "枫林灯语" 无线电)
          ("https://blog.douchi.space/index.xml" :title "椒盐豆豉")
          ("https://justgoidea.com/rss.xml" :title "槿呈 Goidea")
          ("https://shuiba.co/feed" :title "水八口")
          ("https://lhasa.icu/rss.xml" :title "游钓四方")
          ("https://weekly.tw93.fun/rss.xml" :title "潮流周刊" weekly)
          ("https://ameow.xyz/feed.xml" :title "猫鱼周刊" weekly)
          ("https://imgradeone.com/blog.xml" :title "真正的自言者一么")
          ("https://chengpeiquan.com/feed.xml" :title "程沛权" tech frontend)
          ("https://thirdshire.com/index.xml" :title "第三夏尔")
          ("https://elliot00.com/rss" :title "编码与禅" emacs tech)
          ("https://caa-ins.org/feed" :title "网络社会研究所" weekly)
          ("https://guozh.net/feed/" :title "老郭种树")
          ("https://luffy.cc/feed" :title "蒙奇日记")
          ("https://1q43.blog/feed/" :title "虹线")
          ("https://ttio.cc/feed.xml" :title "記緒漂流")
          ("https://ioerr.github.io/index.xml" :title "读写错误")
          ("https://blog.ops-coffee.com/feed.xml" :title "运维咖啡吧")
          ("https://goldenriver.site/index.xml" :title "金色河流")
          ("https://blog.helenchong.omg.lol/zh/feed.xml" :title "银河花园" 马来西亚)
          ("https://www.ctling.com/atom.xml" :title "閒人筆記" 台湾)
          ("https://www.chenrui.com/feed.php" :title "陈锐")
          ("https://www.gaotianchi.com/feed.xml" :title "高天驰")
          ("https://www.tortorse.com/atom.xml" :title "愆伏")
          ("https://perthirtysix.com/rss.xml" :title "PerThirtySix")
          ("https://shkspr.mobi/blog/feed/atom/" :title "Terence Eden" tech)
          ("https://warandpeas.com/feed/" :title "War and Peas" anime)
          ("https://blog.ikukaroom.com/feed/" :title "ikuka" newsletter 台湾 日文)
          ("https://travlog.wei-lee.me/feeds/all.atom.xml" :title "李唯/那些沒人在乎的事" :no-update t 台湾 anime)
          ("https://blog.wei-lee.me/feeds/all.atom.xml" :title "李唯/不寫下來的東西都會被遺忘" :no-update t 台湾 tech)
          ("https://scrubbyinabox.substack.com/feed" :title "刷比小廢報" newsletter)
          ("https://マリウス.com/index.xml" :title "マリウス")
          ("https://wiwi.blog/blog/rss.xml" :title "Wiwi" 台湾 blogblogClub)
          ("https://itsfridayimnotinlove.substack.com/feed" :title "It's Friday I'm (not) in love" newsletter)
          ("https://usefulfictions.substack.com/feed" :title "Useful Fictions" newsletter)
          ("https://staystaystay.substack.com/feed" :title "Stay Stay Stay" newsletter people)
          ("https://jakearchibald.com/posts.rss" :title "Jake Archibald" frontend)
          ("https://patrickbrosset.com/feed.xml" :title "Patrick Brosset" frontend)
          ("https://www.kevinpowell.co/newsletter.xml" :title "Kevin Powell" frontend css)
          ("https://explorationsofstyle.com/feed/" :title "Explorations of Style" writing academic)
          ("https://www.jonafato.com/feed.xml" :title "jonafato" tech python)
          ("https://planet.emacslife.com/atom.xml" :title "Planet Emacslife" feeds emacs)
          ("https://emacsair.me/feed.xml" :title "Emacsair" emacs)
          ("https://tkdodo.eu/blog/rss.xml" :title "TkDodo" Frontend)
          ("https://brennan.day/feed.xml" :title "brennan.day" blaugust2026)
          ("https://schafe-sind-bessere-rasenmaeher.de/index.xml" :title "Schafe sind bessere Rasenmäher")
          ("https://lazybea.rs/index.xml" :title "Lazybear" interview)
          ("https://kwon.nyc/notes/index.xml" :title "Kwon.nyc")
          ("https://walknotes.com/feed/" :title "Walknotes")
          ("http://winnielim.org/feed/?cat=2%2C4%2C8" :title "Winnie Lim")
          ("https://vhbelvadi.com/rss" :title "V.H. Belvadi")
          ("https://webcurios.co.uk/feed/" :title "Web Curios" zine)
          ("https://www.jackcheng.com/sunday/rss/" :title "Jack Cheng" zine)
          ("https://whitep4nth3r.com/feed.xml" :title "Salma Alam-Naylor" tech)
          ("https://hexedhearth.net/feed/rss/" :title "Hexed Hearth")
          ("https://localghost.dev/feed.xml" :title "Localghost")
          ("https://e89295.com/blog/atom.xml" :titie "我的部落格" 台湾)
          ("https://paddletonightside.blogspot.com/feeds/posts/default" :title "夜裡擺渡的幽靈船" 台湾)
          ("https://theprivacydad.com/blog/" :title "Privacy Dad" privacy)
          ("https://moonwriting.blog/feed.xml" :title "moonwriting")
          ("https://jamesg.blog/feeds/posts.xml" :title "James' Coffee Blog" :no-update t)
          ("https://matling.fit/atom.xml" :title "物灵")
          ("https://writings.hongminhee.org/feed.en.xml" :title "Hong Minhee on Things")
          ("https://alexhsu.com/rss.xml" :title "Alex Hsu" 台湾)
          ("https://bkyd.kill.jp/N/feed/" :title "新裏庭" 日語)
          ("https://litter.leaflet.pub/atom" :title "leaf litter" zine)
          ("https://danq.me/feed/" :title "Dan Q" tech)
          ("https://duo3.ink/atom.xml" :title "123哆3")
          ("https://cleberg.net/feed.xml" :title "Christian Cleberg")
          ("https://absurdpirate.bearblog.dev/feed/" :title "Absurd Pirate")
          ("https://unstory.eu/feed.json" :title "unstory" :no-update t)
          ;; no-update
          ("https://feeds.feedblitz.com/alearningaday&x=1" :title "A Learning Day Feed" :no-update t)
          ("https://seths.blog/feed/" :title "SETH'S BLOG")
          ("https://amf.didiermary.fr/feed/" :title "African Music Forum" :no-update t music)
          ("https://www.newcommute.net/feed?format=rss" :title "New Commute" :no-update t music album)
          ("http://xahlee.info/emacs/emacs/blog.xml" :title "Xah Emacs Blog" :no-update t emacs)
          ("https://blast-o-rama.com/rss" :title "blast-o-rama. | Marty Day" :no-update t)
          ("https://2cat.net/feed/" :title "猫鱼" :no-update t)
          ("https://www.hecaitou.com/feeds/posts/default" :title "和菜头" :no-update t)
          ("https://www.changhai.org/feed.xml" :title "卢昌海个人主页" :no-update t)
          ("https://kagi.com/api/v1/smallweb/feed/" :title "Kagi Small Web" :no-update t :fetch-link t feeds blog)
          ("https://bubbles.town/feed" :title "Bubble Main Feed" :no-update t feeds blog)
          ("https://feeds.feedburner.com/brainpickings/rss" :title "The Marginalian" :no-update t book)
          ("https://feeds.feedburner.com/TroyHunt" :title "Troy Hunt's Blog" :no-update t weekly)
          ("https://www.cloudberryrecords.com/blog/?feed=rss2" :title "Cloudberry Cake Proselytism" :no-update t music)
          ("https://www.fullmoonfiberart.com/feed" :title "Full Moon Fiber Art" :no-update t)
          ("https://lawtee.com/index.xml" :title "老 T 博客" :no-update t)
          ("https://www.quantamagazine.org/feed/" :title "Quanta Magazine" :no-update t zine weekly)
          ("https://idle.news/feed.xml" :title "The Idle Gazette" :no-update t weekly)
          ("https://www.wikimoe.com/rss" :title "维基萌" :no-update t anime 圣地巡礼)
          ("https://francescrossley.com/feed/?type=rss" :title "What the Fran" :no-update t blaugust2026)
          ("https://joelchrono.xyz/feed.xml" :title "Joelchrono's Blog" :no-update t game)
          ;; blaugust 2026
          ("http://fyr.io/feed" :title "fyr.io" blaugust2026 new-feeds)
          ("https://granary.io/url?input=html&output=rss&url=https://asteriisms.com/blog" :title "Aster's Asterisms" blaugust2026 new-feeds)
          ("https://davehenry.blog/atom.xml" :title "Dave Henry Blog" blaugust2026 new-feeds)
          ("https://emmajuettner.com/feed/rss.xml" :title "Emma Juettner’s Blog" blaugust2026 new-feeds)
          ("https://quailcreations.ca/?feed=rss2" :title "Quail Creations" blaugust2026 new-feeds)
          ("https://lameazoid.com/feed/" :title "Lameazoid.com" blaugust2026 new-feeds)
          ("https://wakanatrium.site/?mode=rss" :title "もうすぐ33歳" blaugust2026 new-feeds)
          ("https://knifesedgeblogs.wordpress.com/feed/" :title "Knifesedge Blogs" blaugust2026 new-feeds)
          ("https://www.containsmoderateperil.com/blog?format=rss" :title "Contains Moderate Peril" blaugust2026 new-feeds)
          ("https://littlelum.neocities.org/RSS.xml" :title "I Can’t Think of a Name for this Website" blaugust2026 new-feeds)
          ("https://mogblog.pika.page/posts_feed" :title "MogBlog" blaugust2026 new-feeds)
          ("https://godless-internets.org/feed" :title "owlblog" blaugust2026 new-feeds)
          ("https://blog.gridranger.dev/feeds/all.atom.xml" :title "Gridranger’s blog" blaugust2026 new-feeds)
          ("https://rieaglenest.wordpress.com/feed/" :title "Riel’s Nest" blaugust2026 new-feeds)
          ("https://www.bongotwisty.blog/index.xml" :title "BongoTwisty" blaugust2026 new-feeds)
          ("https://thekeerok.neocities.org/feed.xml" :title "keeroks space" blaugust2026 new-feeds)
          ("https://luckyinstar.neocities.org/feed.xml" :title "Lucky Instar" blaugust2026 new-feeds biologist)
          ("https://pinkway.mataroa.blog/rss/" :title "Pinkway" blaugust2026 new-feeds)
          ("https://www.ryanpatrickrandall.com/feed.xml" :title "Ryan Patrick Randall" blaugust2026 new-feeds)
          ("https://endgameviable.com/index.xml" :title "Endgame Viable" blaugust2026 new-feeds game)
          ("https://kaylriene.com/feed/" :title "Kayriene" blaugust2026 new-feeds)
          ("https://welshtroll.co.uk/feed/" :title "Point, Click, Repeat" blaugust2026 new-feeds)
          ("https://wcrobinson.org/feed/" :title "WCRobinson" blaugust2026 new-feeds)
          ("https://nerdgirlthoughts.game.blog/feed/" :title "Nerd Girl Thoughts" blaugust2026 new-feeds)
          ("https://82mhz.net/index.xml" :title "82MHz" blaugust2026 new-feeds)
          ("https://taylorfilmcritic.wordpress.com/feed/" :title "Taylor film crit" blaugust2026 new-feeds)
          ("https://christirichards.com/rss.xml" :title "ChristiRichards.com" blaugust2026 new-feeds)
          ("https://lyonsinbeta.com/feed.xml" :title "Lyons in Beta" blaugust2026 new-feeds)
          ("https://geekonaharley.org/feed/" :title "Geek on a Harley" blaugust2026 new-feeds motorcycle)
          ("https://varunbarad.com/feed.xml" :title "Varun Barad" blaugust2026 new-feeds)
          ("https://blog.marqaroll.com/feeds/posts/default" :title "Mar Qaroll’s The Marrowing!" blaugust2026 new-feeds)
          ("https://whyigame.wordpress.com/feed/" :title "Why I Game" blaugust2026 new-feeds)
          ("https://quinndaedal.com/feed.xml" :title "Quinn Daedal – Blog" blaugust2026 new-feeds)
          ("https://themakerdad.com/rss/" :title "The Maker Dad" blaugust2026 new-feeds)
          ("https://www.bytevortex.tech/rss/" :title "Byte Vortex" blaugust2026 new-feeds game)
          ("https://tallywinkle.bearblog.dev/feed/?type=rss" :title "coffee spills" blaugust2026 new-feeds)
          ("https://ben.ramsey.dev/feeds/blog.rss" :title "Ben Ramsey" blaugust2026 new-feeds)
          ("https://26g.netlify.app/feed.xml" :title "26g" blaugust2026 new-feeds)
          ("https://392ms.witchserver.jp/kb/?mode=rss" :title "392ms" blaugust2026 new-feeds)
          ("https://alessandrocuzzocrea.com/feed.xml" :title "Alessandro Cuzzocrea" blaugust2026 new-feeds)
          ("https://blog.spencermagnusson.com/feed.xml" :title "Beyond the Horizon" blaugust2026 new-feeds game)
          ("https://blog.x2600.cc/feed/" :title "blog.x2600.cc" blaugust2026 new-feeds)
          ("https://burgeonlab.com/all/feed.xml" :title "BurgeonLab" blaugust2026 new-feeds)
          ("https://tallywinkle.bearblog.dev/feed/" :title "coffee spills" blaugust2026 new-feeds)
          ("https://davehenry.blog/feeds/" :title "Dave Henry Blog" blaugust2026 new-feeds)
          ("http://gregorlove.com/articles.atom" :title "gRegorLove.com" blaugust2026 new-feeds)
          ("https://heartsoulmachine.com/feed.xml" :title "Heart Soul Machine" blaugust2026 new-feeds)
          ("https://jak2k.eu/feed.xml" :title "Jak2k’s Website" blaugust2026 new-feeds)
          ("https://kaigulliksen.com/feed.xml" :title "Kai Gulliksen" blaugust2026 new-feeds)
          ("https://thekeerok.neocities.org/feed.xml " :title "keeroks space" blaugust2026 new-feeds)
          ("https://medium.com/feed/@audreyzetta" :title "Medium" blaugust2026 new-feeds)
          ("https://michcia.bearblog.dev/feed/" :title "michcia’s notes" blaugust2026 new-feeds)
          ("https://noisydeadlines.net/feed/" :title "Noisy Deadlines" blaugust2026 new-feeds)
          ("http://feeds.feedburner.com/VanderwalnetOffTheTop" :title "Off the Top" blaugust2026 new-feeds)
          ("https://orbitalmartian.polymaths.page/feed.xml" :title "OrbitalMartian" blaugust2026 new-feeds)
          ("https://personalinfocloud.com/feed/" :title "Personal InfoCloud" blaugust2026 new-feeds)
          ("https://prin.lu/feed.xml" :title "prin.lu" blaugust2026 new-feeds)
          ("https://blog.nyman.re/feed.xml" :title "re: nyman" blaugust2026 new-feeds)
          ("https://sweaterpockets.bearblog.dev/feed/" :title "SweaterPockets" blaugust2026 new-feeds)
          ("https://tabitha.computer/feed/" :title "Tabitha" blaugust2026 new-feeds)
          ("https://francescrossley.com/feed/" :title "What the Fran" blaugust2026 new-feeds)
          ("https://wrywriter.ca/posts_feed" :title "Wry Writer" blaugust2026 new-feeds)
          ("https://zacharykai.net/assets/rss.xml" :title "Zachary Kai" blaugust2026 new-feeds)
          ("https://wakupanbouquet.hatenablog.com/feed" :title "わくパンの思考のかけら" blaugust2026 new-feeds)
          ("https://coop-setsugen.com/feed.xml" :title "コーポ雪原" blaugust2026 new-feeds)
          ("https://bavatuesdays.com/feed/" :title "bavatuesdays" blaugust2026 new-feeds)
          ("https://www.beyondtannhausergate.com/feed/" :title "Beyond Tannhauser Gate" blaugust2026 new-feeds)
          ("https://taterinx.bearblog.dev/feed/" :title "Biggus Bloggus" blaugust2026 new-feeds)
          ("https://www.crosenthal.com/chrome/feed.xml" :title "It’s Just This Little Chromium Switch Here" blaugust2026 new-feeds)
          ("https://lostletters.neocities.org/feed.xml" :title "Lost Letters" blaugust2026 new-feeds)
          ("https://muttthecowcat.neocities.org/rss.xml" :title "muttthecowcat" blaugust2026 new-feeds)
          ("https://nosrednayduj.dreamwidth.org/data/rss" :title "nosrednayduj’s blog" blaugust2026 new-feeds)
          ("https://nullish.smol.pub/atom.xml" :title "Nullish" blaugust2026 new-feeds)
          ("https://rachonaut.com/feed/" :title "rachonaut" blaugust2026 new-feeds)
          ("https://sals.place/feed/feed.xml" :title "Sal’s" blaugust2026 new-feeds)
          ("https://dearangelblog.tumblr.com/rss" :title "Tumblr" blaugust2026 new-feeds)
          ("https://20ilyapril.wordpress.com/feed/" :title "20ilyApril" blaugust2026 new-feeds)
          ("https://blog.agnes.love/rss/" :title "Agnes the Alien’s blog" blaugust2026 new-feeds)
          ("http://devz.cl/index.xml" :title "devz.cl" blaugust2026 new-feeds)
          ("https://drjan.org/feed/" :title "From the keyboard of Dr Jan" blaugust2026 new-feeds)
          ("https://www.ivyrun.com/inanotherplace/?feed=rss2" :title "http://www.ivyrun.com/inanotherplace" blaugust2026 new-feeds)
          ("https://lysurps.neocities.org/rss.xml" :title "lysurps" blaugust2026 new-feeds)
          ("https://michaelharley.net/posts/feed.xml" :title "Michael Harley" blaugust2026 new-feeds)
          ("https://pourthecoffee.bearblog.dev/feed/" :title "Pour The Coffee" blaugust2026 new-feeds)
          ("https://pux.nehukon.de/box/feed.php?f=notes" :title "puxped’s station" blaugust2026 new-feeds)
          ("https://sals.place/index.xml" :title "Sal’s" blaugust2026 new-feeds)
          ("https://srijan.ch/feed/all.xml" :title "Srijan’s Home" blaugust2026 new-feeds)
          ("https://westkarana.blog/feed/" :title "West Karana" blaugust2026 new-feeds)
          ("https://www.omz13.com/feed.atom" :title "words, essays, and more" blaugust2026 new-feeds)
          ;; end
          ))

  (with-eval-after-load 'elfeed
    (defun elfeed-tree--sort (nodes)
      "Sort tree NODES by name."
      (sort nodes (lambda (x y)
                    (string< (car x) (car y))))))

  (add-hook 'elfeed-new-entry-hook
            (elfeed-make-tagger :before "1 months ago"
                                :remove 'unread))


  (defun spike-leung/preview-elfeed-with-olivetti ()
    "Preview elfeed with `olivetti-mode'."
    (olivetti-mode)
    (olivetti-set-width 80)
    (visual-line-mode))
  (add-hook 'elfeed-show-mode-hook #'spike-leung/preview-elfeed-with-olivetti))



(defun spike-leung/elfeed-toggle-unread ()
  "Toggle elfeed unread status."
  (interactive)
  (if (string-match-p "+unread" elfeed-search-filter)
      (elfeed-search-set-filter (string-replace "+unread" "-unread" elfeed-search-filter))
    (elfeed-search-set-filter (string-replace "-unread" "+unread" elfeed-search-filter))))



(defun spike-leung/elfeed-reading-list ()
  "Generate selected Elfeed entries as reading list.  Auto push to git."
  (interactive nil elfeed-search-mode)
  (let ((repo-dir (expand-file-name "~/git/reading-list"))
        (entries (elfeed-search-selected)))
    (with-temp-buffer
      (goto-char (point-min))
      (insert (format "#+title: Reading list\n"))
      (insert "#+options: html-postamble:nil\n")
      (insert "#+html_head_extra: <link rel=\"stylesheet\" href=\"./main.css\" />\n")
      (insert "#+html_head_extra: <script defer src=\"./main.js\"></script>\n")
      (insert "@@html:<div class=\"action\">@@")
      (insert "[[https://translate.kagi.com/https://spike-leung.github.io/reading-list/index.html?to=zh_cn&kt_quality=best][Translate]]")
      (insert "@@html:<span><input type=\"checkbox\" id=\"like\"/><label for=\"like\" class=\"like-label\"></label></span>@@")
      (insert "@@html:</div>@@")
      (insert "\n\n")
      (dolist (entry entries)
        (let* ((link (elfeed-entry-link entry))
               (title (elfeed-entry-title entry))
               (like-button (format "@@html:<span class=\"like-button\" data-id=\"%s\"></span>@@" link)))
          (insert (format "- %s %s" (org-link-make-string link title) like-button)))
        (insert "\n"))
      (insert "這是从 [[https://github.com/emacs-elfeed/elfeed][elfeed]] 导出的个人訂閱数据，仅方便个人使用。\n\n
具体見： [[https://taxodium.ink/export-elfeed-selected-entries-to-github-page-as-reading-list.html][导出 Elfeed 选中条目到 GitHub Page 作为 Reading List]]。\n\n")
      (org-mode)
      (org-export-to-file 'html "~/git/reading-list/index.html"))
    (message "Entries export to index.html")
    (let ((default-directory repo-dir))
      (unless (file-directory-p (expand-file-name ".git" repo-dir))
        (user-error "Not a git repository: %s" repo-dir))
      (message "Syncing with origin...")
      (if (= 0 (shell-command "git pull --ff-only --no-rebase"))
          (message "Synced with origin.")
        (user-error "Git pull failed; resolve manually in %s" repo-dir))
      (shell-command "git add index.html")
      (let ((status (shell-command-to-string "git status --porcelain index.html")))
        (if (string-empty-p status)
            (message "No changes to commit.")
          (let ((commit-msg ":memo: update reading list"))
            (shell-command (format "git commit -m \"%s\"" commit-msg))
            (message "Pushing to origin...")
            (if (= 0 (shell-command "git push" nil nil))
                (message "Add entries and pushed to origin.")
              (message "Add entries but push failed."))))))))



(defconst spike-leung/elfeed-translate-prompt "translate to chinese. only response translated content."
  "System prompt for translating elfeed entry title via gptel.")

(defun spike-leung/elfeed--display-side-by-side (buffer)
  "Display BUFFER to the right of *elfeed-search* window."
  (if-let ((win (get-buffer-window "*elfeed-search*")))
      (display-buffer buffer
                      '((display-buffer-in-side-window)
                        (side . right)
                        (window-width . 0.5)))
    (pop-to-buffer buffer)))

(defun spike-leung/elfeed--scroll-all-cleanup ()
  "Disable `scroll-all-mode' when neither elfeed nor translate window remains."
  (unless (and (get-buffer-window "*elfeed-search*" 'visible)
               (get-buffer-window "*gptel-elfeed-translate*" 'visible))
    (scroll-all-mode -1)
    (remove-hook 'window-configuration-change-hook
                 #'spike-leung/elfeed--scroll-all-cleanup)))

(defun spike-leung/elfeed-translate-entries ()
  "Translate selected elfeed entries with gptel."
  (interactive nil elfeed-search-mode)
  (require 'gptel)
  (let ((entries (elfeed-search-selected)))
    (unless entries
      (user-error "No entries selected"))
    (let* ((titles (mapcar #'elfeed-entry-title entries))
           (prompt (mapconcat #'identity titles "\n"))
           (buf (get-buffer-create "*gptel-elfeed-translate*")))
      (with-current-buffer buf
        (erase-buffer)
        (insert "Translating...")
        (scroll-all-mode 1)
        (add-hook 'window-configuration-change-hook
                  #'spike-leung/elfeed--scroll-all-cleanup)
        (setq-local gptel--request-params '(:reasoning (:effort "none"))))
      (spike-leung/elfeed--display-side-by-side buf)
      (gptel-request prompt
        :buffer buf
        :position (with-current-buffer buf (point-max))
        :system spike-leung/elfeed-translate-prompt
        :callback (lambda (response _info)
                    (when (stringp response)
                      (with-current-buffer buf
                        (erase-buffer)
                        (insert response)
                        (whitespace-cleanup)
                        (org-mode)
                        (gptel-mode))))))))



(provide 'init-elfeed)
;;; init-elfeed.el ends here
