;;; init-ui.el --- UI related setting -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:



;; Stop C-z from minimizing windows under OS X
(defun sanityinc/maybe-suspend-frame ()
  (interactive)
  (unless (and *is-a-mac* window-system)
    (suspend-frame)))

(keymap-global-set "C-z" 'sanityinc/maybe-suspend-frame)



;; Window size and features

(when (fboundp 'tool-bar-mode)
  (tool-bar-mode -1))
(when (fboundp 'set-scroll-bar-mode)
  (set-scroll-bar-mode nil))

(menu-bar-mode -1)

;; hide titlebar
;; see: https://github.com/d12frosted/homebrew-emacs-plus#emacs-29-1
(add-to-list 'default-frame-alist '(undecorated-round . t))



;; text related

;; Change global font size easily
(use-package default-text-scale
  :ensure
  :init
  (default-text-scale-mode))

(set-face-attribute 'default nil :height 220 :font "Iosevka")
(dolist (fontset '(han kana hangul cjk-misc))
  (set-fontset-font "fontset-default" fontset
                    (font-spec :family "I.Ming")))



;; you can insert page-break-lines with "C-q C-l"
(use-package page-break-lines
  :diminish
  :defer nil
  :hook ((after-init . global-page-break-lines-mode)
         ;; browse-kill-ring use "^L" (page-break-lines) also
         (browse-kill-ring-mode . page-break-lines-mode)))



;; theme
(use-package modus-themes
  :config
  (setq modus-themes-italic-constructs t
        modus-themes-bold-constructs t
        modus-themes-disable-other-themes t)
  (setq modus-themes-common-palette-overrides
        '((bg-prose-block-contents unspecified)
          (bg-prose-block-delimiter unspeficied)
          (fg-prose-block-delimiter fg-dim)))

  (defun spike-leung/modus-themes-margin-override (&rest _)
    "Make margin background the same as `defaults'.
     Margin will act as padding in `olivetti-mode'.
     Add this to the `modus-themes-post-load-hook'."
    (let ((bg (face-background 'default)))
      (custom-set-faces
       `(margin ((t :background ,bg :foreground ,bg))))))

  (add-hook 'modus-themes-post-load-hook #'spike-leung/modus-themes-margin-override))

(use-package ef-themes)
(use-package doric-themes)

(defun spike-leung/load-theme-by-time (light-fn dark-fn)
  "Call LIGHT-FN  to load light themes from 8:00a.m to 6:00p.m.
otherwise, call DARK-FN to load dark themes."
  (let ((hour (string-to-number (format-time-string "%H"))))
    (funcall (if (and (>= hour 8) (< hour 18)) light-fn dark-fn))))

(defun spike-leung/themes-load-random (&optional background-mode)
  "Random load themes.

Use `ef-themes' for Monday,Tuesday,Wednesday.
Use `modus-themes' on Thursday, Friday.
Use `doric-themes' on Saturday, Sunday.
Use light themes at day, use dark themes at night.

With optional BACKGROUND-MODE as a prefix argument, prompt to limit the
set of themes to either dark or light variants."
  (require 'modus-themes)
  (require 'ef-themes)
  (require 'doric-themes)
  (let ((week (string-to-number (format-time-string "%u"))))
    (cond
     ((<= week 3)
      (cond
       ((eq background-mode 'light) (ef-themes-load-random-light))
       ((eq background-mode 'dark) (ef-themes-load-random-dark))
       (t (spike-leung/load-theme-by-time #'ef-themes-load-random-light #'ef-themes-load-random-dark))))
     ((<= week 5)
      (if background-mode
          (modus-themes-load-random background-mode)
        (spike-leung/load-theme-by-time
         (lambda () (modus-themes-load-random 'light))
         (lambda () (modus-themes-load-random 'dark)))))
     (t
      (if background-mode
          (doric-themes-load-random background-mode)
        (spike-leung/load-theme-by-time
         (lambda () (doric-themes-load-random 'light))
         (lambda () (doric-themes-load-random 'dark))))))))

(defvar spike-leung/current-theme-background-mode 'light
  "Current theme's background-mode value，can be 'light or 'dark, default to 'light.")

(defun light()
  "Load random light themes."
  (interactive)
  (setq spike-leung/current-theme-background-mode 'light)
  (spike-leung/themes-load-random 'light)
  (modify-frame-parameters nil `((alpha . 100))))

(defun dark()
  "Load random dark themes."
  (interactive)
  (setq spike-leung/current-theme-background-mode 'dark)
  (spike-leung/themes-load-random 'dark)
  ;; 暗色主题适当降低透明度，看起来更好看。不同的主题适合不同的透明度。
  (let ((theme (format "%s" custom-enabled-themes)))
    (cond
     ((string-match-p "modus-" theme)
      (modify-frame-parameters nil `((alpha . 80))))
     ((string-match-p "ef-" theme)
      (modify-frame-parameters nil `((alpha . 92))))
     ((string-match-p "doric-" theme)
      (modify-frame-parameters nil `((alpha . 95)))))))

;; 要在 desktop 加载后再执行，避免被 desktop 记录的主题覆盖，导致混乱
(add-hook 'desktop-after-read-hook #'spike-leung/themes-load-random)

(keymap-global-set "<f5>" #'(lambda ()
                              (interactive)
                              (spike-leung/load-theme-by-time #'light #'dark)))

(defun spike-leung/save-org-html-htmlize-generate-css (&rest _)
  "Save content generated by `org-html-htmlize-generate-css' to files."
  (with-current-buffer "*html*"
    (cond
     ((eq spike-leung/current-theme-background-mode 'light)
      (write-region nil nil "~/git/taxodium/scripts/light.txt" nil))
     ((eq spike-leung/current-theme-background-mode 'dark)
      (write-region nil nil "~/git/taxodium/scripts/dark.txt" nil))))
  (kill-buffer "*html*"))

(advice-remove 'org-html-htmlize-generate-css #'spike-leung/save-org-html-htmlize-generate-css)
(advice-add 'org-html-htmlize-generate-css :after #'spike-leung/save-org-html-htmlize-generate-css)



;;; icons
(use-package nerd-icons :defer nil)



(use-package hl-line
  :hook ((ibuffer-mode . hl-line-mode)
         (dired-mode . hl-line-mode)
         (org-agenda-mode . hl-line-mode)))



;; opacity

(defun sanityinc/adjust-opacity (frame incr)
  "Adjust the background opacity of FRAME by increment INCR."
  (unless (display-graphic-p frame)
    (error "Cannot adjust opacity of this frame"))
  (let* ((oldalpha (or (frame-parameter frame 'alpha) 100))
         ;; The 'alpha frame param became a pair at some point in
         ;; emacs 24.x, e.g. (100 100)
         (oldalpha (if (listp oldalpha) (car oldalpha) oldalpha))
         (newalpha (+ incr oldalpha)))
    (when (and (<= frame-alpha-lower-limit newalpha) (>= 100 newalpha))
      (modify-frame-parameters frame (list (cons 'alpha newalpha))))))

(keymap-global-set "C-M-8" (lambda () (interactive) (sanityinc/adjust-opacity nil -2)))
(keymap-global-set "C-M-9" (lambda () (interactive) (sanityinc/adjust-opacity nil 2)))
(keymap-global-set "C-M-7" (lambda () (interactive) (modify-frame-parameters nil `((alpha . 100)))))



;; Visually highlight the selected buffer.

(use-package dimmer
  :diminish
  :hook (after-init . dimmer-mode)
  :config
  (setq-default dimmer-fraction 0.25))



(use-package spacious-padding
  :ensure t
  :defer nil
  :config
  (spacious-padding-mode 1))



(when (fboundp 'pixel-scroll-precision-mode)
  (pixel-scroll-precision-mode))



;; Set some mode to fullfrmae

(defun sanityinc/display-buffer-full-frame (buffer alist)
  "If it's not visible, display buffer full-frame, saving the prior window config.
The saved config will be restored when the window is quit later.
BUFFER and ALIST are as for `display-buffer-full-frame'."
  (let ((initial-window-configuration (current-window-configuration)))
    (or (display-buffer-reuse-window buffer alist)
        (let ((full-window (display-buffer-full-frame buffer alist)))
          (prog1
              full-window
            (set-window-parameter full-window 'sanityinc/previous-config initial-window-configuration))))))

(defun sanityinc/maybe-restore-window-configuration (orig &optional kill window)
  (let* ((window  (or window (selected-window)))
         (to-restore (window-parameter window 'sanityinc/previous-config)))
    (set-window-parameter window 'sanityinc/previous-config nil)
    (funcall orig kill window)
    (when to-restore
      (set-window-configuration to-restore))))

(advice-add 'quit-window :around 'sanityinc/maybe-restore-window-configuration)

(defmacro sanityinc/fullframe-mode (mode)
  "Configure buffers that open in MODE to display in full-frame."
  `(add-to-list 'display-buffer-alist
                (cons (cons 'major-mode ,mode)
                      (list 'sanityinc/display-buffer-full-frame))))

(dolist (mode '(package-menu-mode magit-status-mode ibuffer-mode))
  (sanityinc/fullframe-mode mode))



(provide 'init-ui)
;;; init-ui.el ends here
